In [1]:
import numpy as np

In [2]:
matriz = np.array([[1,0,0,1],
                   [2,2,2,5],
                   [-3,2,0,0],
                   [1,0,-1,4]])

In [3]:
matriz

array([[ 1,  0,  0,  1],
       [ 2,  2,  2,  5],
       [-3,  2,  0,  0],
       [ 1,  0, -1,  4]])

In [4]:
print(matriz)

[[ 1  0  0  1]
 [ 2  2  2  5]
 [-3  2  0  0]
 [ 1  0 -1  4]]


In [5]:
matriz2 = np.array([[1,0,3,1],
                   [2,2,2,5],
                   [-1,3,0,0],
                   [9,0,-1,4]])

In [6]:
matriz2

array([[ 1,  0,  3,  1],
       [ 2,  2,  2,  5],
       [-1,  3,  0,  0],
       [ 9,  0, -1,  4]])

In [7]:
print(matriz2)

[[ 1  0  3  1]
 [ 2  2  2  5]
 [-1  3  0  0]
 [ 9  0 -1  4]]


In [8]:
soma = matriz + matriz2

In [9]:
print(soma)

[[ 2  0  3  2]
 [ 4  4  4 10]
 [-4  5  0  0]
 [10  0 -2  8]]


In [10]:
sub = matriz - matriz2

In [12]:
print(sub)

[[ 0  0 -3  0]
 [ 0  0  0  0]
 [-2 -1  0  0]
 [-8  0  0  0]]


In [13]:
mult_escalar = matriz * 3

In [14]:
print(mult_escalar)

[[ 3  0  0  3]
 [ 6  6  6 15]
 [-9  6  0  0]
 [ 3  0 -3 12]]


In [15]:
div = matriz / 2

In [16]:
print(div)

[[ 0.5  0.   0.   0.5]
 [ 1.   1.   1.   2.5]
 [-1.5  1.   0.   0. ]
 [ 0.5  0.  -0.5  2. ]]


In [17]:
m = np.dot(matriz, matriz2)

In [18]:
print(m)

[[10  0  2  5]
 [49 10  5 32]
 [ 1  4 -5  7]
 [38 -3 -1 17]]
