In [1]:
import numpy as np

In [18]:
a = np.array([
    [1,5,3],
    [3,2,1], 
    [1,1,1]
])

In [19]:
y = np.array([[1],
             [0],
             [1]
])

In [20]:
print(a)

[[1 5 3]
 [3 2 1]
 [1 1 1]]


In [21]:
print(y)

[[1]
 [0]
 [1]]


In [8]:
a_inv = np.linalg.inv(a)

In [9]:
print(a_inv)

[[-0.16666667  0.33333333  0.16666667]
 [ 0.33333333  0.33333333 -1.33333333]
 [-0.16666667 -0.66666667  2.16666667]]


In [10]:
#calculando resultado

In [11]:
x = np.dot(a_inv, y)
print(x)

[[ 0.]
 [-1.]
 [ 2.]]


In [24]:
#resolvendo de forma alternativa

x = np.linalg.solve(a,y)
print(x)

[[-7.40148683e-17]
 [-1.00000000e+00]
 [ 2.00000000e+00]]


In [26]:
#Determinantes

m = np.array([
    [1,0,1],
    [2,2,2],
    [-1,4,-2]
])

In [27]:
print(m)

[[ 1  0  1]
 [ 2  2  2]
 [-1  4 -2]]


In [28]:
det =  np.linalg.det(m)

In [29]:
print(det)

-1.9999999999999998


In [30]:
import math as m

In [31]:
print(m.ceil(det))

-1


In [32]:
print(round(det))

-2
