In [1]:
import numpy as np

In [2]:
 a= np.array([[0,1], [3,0]])

In [3]:
print(a)

[[0 1]
 [3 0]]


In [4]:
#Matriz transposta, linhas viram colunas, colunas viram linhas

In [5]:
t = a.transpose()

In [6]:
print(t)

[[0 3]
 [1 0]]


In [7]:
#Operador T

In [8]:
r = a.T

In [9]:
print(r)

[[0 3]
 [1 0]]


In [10]:
#Matriz identidade -> Matriz quadrada , n de linhas = n de colunas
# A diagonal princiapl é opara todos os elemtnos, o restante é igual a zero
[ 
    [1,0,0],
    [0,1,0],
    [0,0,1]
]

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [11]:
id = np.eye(3)

In [12]:
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
id10 = np.eye(10)

In [14]:
print(id10)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [15]:
#Matriz inversa


$$A . A^{-1} = I$$

In [16]:
b = np.array([[0,1], [3,0]])

In [17]:
i = np.eye(2)

In [23]:
#calculando a inversa
b_inv = np.linalg.inv(b)

In [24]:
print(b)

[[0 1]
 [3 0]]


In [25]:
print(b)
print()
print(b_inv)

[[0 1]
 [3 0]]

[[0.         0.33333333]
 [1.         0.        ]]


In [26]:
print(b*b_inv)

[[0.         0.33333333]
 [3.         0.        ]]
